<a href="https://colab.research.google.com/github/Dhnxz/Data-cleaning/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd

df = pd.read_csv('uber_delivery_tips_dataset.csv')

In [30]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1214 entries, 0 to 1213
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1214 non-null   object
 1   time                  1214 non-null   float64
 2   fare                  1214 non-null   float64
 3   tip                   1214 non-null   float64
 4   earnings              1214 non-null   float64
 5   distance              1214 non-null   float64
 6   duration              1214 non-null   object
 7   restaurant_address    1214 non-null   object
 8   points                1214 non-null   int64
 9   deliveries_count      1214 non-null   int64
 10  dropoff_latitude      1214 non-null   float64
 11  dropoff_longitude     1214 non-null   float64
 12  restaurant_latitude   1214 non-null   float64
 13  restaurant_longitude  1214 non-null   float64
 14  weekday               1214 non-null   int64
 15  weekday_name          1214 non-null   object
 16  is_weekend            1214 non-null   bool
 17  is_holiday            1214 non-null   bool
 18  duration_min          1214 non-null   float64
 19  speed_mph             1214 non-null   float64
 20  part_of_day           1214 non-null   object
 21  earnings_per_mile     1214 non-null   float64
 22  earnings_per_hour     1214 non-null   float64
 23  tip_pct               1214 non-null   float64
 24  driver_binary         1214 non-null   int64
dtypes: bool(2), float64(14), int64(4), object(5)
memory usage: 220.6+ KB

,time,fare,tip,earnings,distance,points,deliveries_count,dropoff_latitude,dropoff_longitude,restaurant_latitude,restaurant_longitude,weekday,duration_min,speed_mph,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
count,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000,1214.000000
mean,13.609143,6.284736,6.537710,12.822446,5.462191,3.995881,1.286656,34.424981,-119.747657,34.425423,-119.742220,3.400329,25.432084,16.984549,3.423016,39.241996,0.494803,0.532949
std,6.997013,4.959356,5.262945,7.357635,4.206426,3.994532,0.556935,0.030337,0.078750,0.011746,0.064267,1.911789,11.667831,51.893216,3.029667,71.029639,0.216337,0.499119
min,0.000000,2.000000,0.000000,2.490000,0.220000,0.000000,1.000000,33.481504,-119.967804,34.394906,-119.884742,0.000000,1.000000,1.163972,0.535032,6.563003,0.000000,0.000000
25%,9.000000,3.200000,3.017500,8.002500,2.490000,1.000000,1.000000,34.415858,-119.817290,34.417589,-119.761575,2.000000,16.983333,7.471376,1.754653,21.105655,0.356314,0.000000
50%,14.500000,4.620000,5.135000,10.650000,4.250000,2.000000,1.000000,34.425202,-119.722163,34.425318,-119.722221,4.000000,23.458333,10.741758,2.571176,28.030665,0.545402,1.000000
75%,20.000000,7.455000,8.587500,15.602500,7.045000,6.000000,1.000000,34.435060,-119.700827,34.436865,-119.696258,5.000000,31.829167,15.367912,4.047343,37.604358,0.654698,1.000000
max,23.500000,59.270000,60.000000,67.150000,27.170000,24.000000,4.000000,34.490806,-119.029663,34.442491,-119.511997,6.000000,60.000000,1333.200000,38.136364,1261.800000,0.941915,1.000000

In [31]:
df.isnull().sum()

date                    0
time                    0
fare                    0
tip                     0
earnings                0
distance                0
duration                0
restaurant_address      0
points                  0
deliveries_count        0
dropoff_latitude        0
dropoff_longitude       0
restaurant_latitude     0
restaurant_longitude    0
weekday                 0
weekday_name            0
is_weekend              0
is_holiday              0
duration_min            0
speed_mph               0
part_of_day             0
earnings_per_mile       0
earnings_per_hour       0
tip_pct                 0
driver_binary           0
dtype: int64

In [32]:
df['tip'] = df['tip'].fillna(0)

In [33]:
df['earnings'] = df['earnings'].fillna(df['earnings'].mean())

In [34]:
df = df.dropna()

In [35]:
df = df.drop_duplicates()

In [36]:
df.dtypes

date                     object
time                    float64
fare                    float64
tip                     float64
earnings                float64
distance                float64
duration                 object
restaurant_address       object
points                    int64
deliveries_count          int64
dropoff_latitude        float64
dropoff_longitude       float64
restaurant_latitude     float64
restaurant_longitude    float64
weekday                   int64
weekday_name             object
is_weekend                 bool
is_holiday                 bool
duration_min            float64
speed_mph               float64
part_of_day              object
earnings_per_mile       float64
earnings_per_hour       float64
tip_pct                 float64
driver_binary             int64
dtype: object

In [37]:
df['part_of_day'] = df['part_of_day'].str.strip()

In [38]:
df = df[df['earnings'] > 0]

In [39]:
df = df[df['earnings'] < 100]

In [40]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 1209 entries, 0 to 1213
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1209 non-null   object
 1   time                  1209 non-null   float64
 2   fare                  1209 non-null   float64
 3   tip                   1209 non-null   float64
 4   earnings              1209 non-null   float64
 5   distance              1209 non-null   float64
 6   duration              1209 non-null   object
 7   restaurant_address    1209 non-null   object
 8   points                1209 non-null   int64
 9   deliveries_count      1209 non-null   int64
 10  dropoff_latitude      1209 non-null   float64
 11  dropoff_longitude     1209 non-null   float64
 12  restaurant_latitude   1209 non-null   float64
 13  restaurant_longitude  1209 non-null   float64
 14  weekday               1209 non-null   int64
 15  weekday_name          1209 non-null   object
 16  is_weekend            1209 non-null   bool
 17  is_holiday            1209 non-null   bool
 18  duration_min          1209 non-null   float64
 19  speed_mph             1209 non-null   float64
 20  part_of_day           1209 non-null   object
 21  earnings_per_mile     1209 non-null   float64
 22  earnings_per_hour     1209 non-null   float64
 23  tip_pct               1209 non-null   float64
 24  driver_binary         1209 non-null   int64
dtypes: bool(2), float64(14), int64(4), object(5)
memory usage: 229.0+ KB

date                    0
time                    0
fare                    0
tip                     0
earnings                0
distance                0
duration                0
restaurant_address      0
points                  0
deliveries_count        0
dropoff_latitude        0
dropoff_longitude       0
restaurant_latitude     0
restaurant_longitude    0
weekday                 0
weekday_name            0
is_weekend              0
is_holiday              0
duration_min            0
speed_mph               0
part_of_day             0
earnings_per_mile       0
earnings_per_hour       0
tip_pct                 0
driver_binary           0
dtype: int64