<a href="https://colab.research.google.com/github/Dhnxz/Data-cleaning/blob/main/Grouping_and_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('uber_delivery_tips_dataset.csv')

In [5]:
df.head()

,date,time,fare,tip,earnings,distance,duration,restaurant_address,points,deliveries_count,...,weekday_name,is_weekend,is_holiday,duration_min,speed_mph,part_of_day,earnings_per_mile,earnings_per_hour,tip_pct,driver_binary
0,2025-06-08,20.0,12.30,1.00,13.30,5.57,26m 24s,McDonald's (146 S Fairview Ave),12,1,...,Sunday,True,False,26.400000,12.659091,Evening,2.387792,30.227273,0.075188,0
1,2025-03-08,0.0,5.93,2.00,7.93,2.59,23 min 36 s,"McDonald's, Cliff Dr",2,1,...,Saturday,True,False,23.600000,6.584746,Night,3.061776,20.161017,0.252207,1
2,2025-06-09,11.0,2.64,3.84,6.48,2.30,25m 18s,Su’s Bowl (Isla Vista),3,1,...,Monday,False,False,25.300000,5.454545,Lunch,2.817391,15.367589,0.592593,0
3,2025-06-09,11.5,5.00,0.00,5.00,5.84,40m 50s,Kaiju Ramen and Curry (Isla Vista),6,2,...,Monday,False,False,40.833333,8.581224,Lunch,0.856164,7.346939,0.000000,0
4,2025-03-09,1.0,2.65,6.44,9.09,1.59,12 min 05 s,"Taco Bell, 821 N Milpas St",1,1,...,Sunday,True,False,12.083333,7.895172,Night,5.716981,45.136552,0.708471,1

In [6]:
df.groupby('part_of_day')['earnings'].mean()

part_of_day
Afternoon    13.363289
Evening      14.247553
Lunch        12.652294
Morning      10.644866
Night        12.646915
Name: earnings, dtype: float64

In [7]:
df.groupby('weekday_name')['earnings'].sum()

weekday_name
Friday       2672.89
Monday       1236.44
Saturday     3381.47
Sunday       2776.30
Thursday     1804.92
Tuesday      1479.64
Wednesday    2214.79
Name: earnings, dtype: float64

In [8]:
df.groupby('part_of_day')['earnings'].agg(['mean', 'max', 'min'])

                  mean    max   min
part_of_day
Afternoon    13.363289  50.23  5.09
Evening      14.247553  67.15  4.01
Lunch        12.652294  63.70  3.00
Morning      10.644866  34.69  2.49
Night        12.646915  42.50  4.03

In [9]:
df.groupby(['part_of_day', 'is_weekend'])['earnings'].mean()

part_of_day  is_weekend
Afternoon    False         12.542273
             True          14.492188
Evening      False         13.311370
             True          15.878323
Lunch        False         11.774103
             True          14.590943
Morning      False         10.166854
             True          11.670000
Night        False         12.428024
             True          12.964783
Name: earnings, dtype: float64

In [10]:
df.groupby('part_of_day').size()

part_of_day
Afternoon     76
Evening      425
Lunch        170
Morning      261
Night        282
dtype: int64

In [11]:
df.groupby('part_of_day')['tip'].mean()

part_of_day
Afternoon    6.893553
Evening      8.009388
Lunch        5.780176
Morning      5.117893
Night        5.994610
Name: tip, dtype: float64

In [12]:
df.groupby('part_of_day')['earnings'].mean().sort_values(ascending=False)

part_of_day
Evening      14.247553
Afternoon    13.363289
Lunch        12.652294
Night        12.646915
Morning      10.644866
Name: earnings, dtype: float64

In [13]:
df.groupby('weekday_name')['earnings'].mean()

weekday_name
Friday       13.102402
Monday       11.039643
Saturday     13.690162
Sunday       14.535602
Thursday     12.800851
Tuesday      11.381846
Wednesday    11.718466
Name: earnings, dtype: float64

In [14]:
df.groupby('is_weekend')['tip'].sum()

is_weekend
False    4798.89
True     3137.89
Name: tip, dtype: float64

In [15]:
df.groupby('part_of_day')['earnings'].mean().sort_values(ascending=False)

part_of_day
Evening      14.247553
Afternoon    13.363289
Lunch        12.652294
Night        12.646915
Morning      10.644866
Name: earnings, dtype: float64

In [16]:
df.groupby('weekday_name').size()

weekday_name
Friday       204
Monday       112
Saturday     247
Sunday       191
Thursday     141
Tuesday      130
Wednesday    189
dtype: int64